### ISSUE TITLE
Software freezes

### ISSUE THREAD

**Issue by L3ungj** [Kai-Guan/BFS-Visualisation#1]
Software freezes with the following input:

testcase.txt
`A:BCG
B:CA
C:AB
Z:Y
Y:Z
G:A`

Entering AZ in the app.

**Comment by Kai-Guan** [comment]
This has to do with the way I check the input.
It checks if A has a neighbor, `True` 
It checks if Z has a neighbor, `True` 
But the problem is that there is no valid path between the two nodes so the program just freezes.
I'll make the BFS do a check somehow but that's gonna take a while.

`if event.key == pygame.K_RETURN:

                if len(text) == 2:

                    if text[0] in letters and text[1] in letters:

                         if nodes[text[0]].neighbours != [] and nodes[text[1]].neighbours != []: #this line

                            start,end = text[0],text[1]
`

**Comment by Kai-Guan** [comment]
Fixed the bug by implementing a check on the `queue` list in the `BFS` function.
